-- Flyway Migration V1: Initial IAM Schema
-- Updated: migrated PKs from UUID to BIGINT to match JPA entities in core-platform

-- ========================================
-- IAM: Roles
-- ========================================
CREATE TABLE IF NOT EXISTS iam_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(500),
    tenant_id   VARCHAR(100),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version     BIGINT        NOT NULL DEFAULT 0,
    UNIQUE (name, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_role_tenant ON iam_role (tenant_id);

-- ========================================
-- IAM: Permissions (simple definitions)
-- ========================================
CREATE TABLE IF NOT EXISTS iam_permission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL UNIQUE,
    description VARCHAR(500)
);

-- ========================================
-- IAM: Role-Permission assignments
-- ========================================
CREATE TABLE IF NOT EXISTS iam_role_permissions (
    role_id       BIGINT NOT NULL REFERENCES iam_role (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_role_permissions_role ON iam_role_permissions (role_id);

-- ========================================
-- IAM: Modules
-- ========================================
CREATE TABLE IF NOT EXISTS iam_module (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL UNIQUE,
    description VARCHAR(500),
    tenant_id   VARCHAR(100),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version     BIGINT        NOT NULL DEFAULT 0
);

-- ========================================
-- IAM: Resources
-- ========================================
CREATE TABLE IF NOT EXISTS iam_resource (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL UNIQUE,
    description VARCHAR(500),
    tenant_id   VARCHAR(100),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version     BIGINT        NOT NULL DEFAULT 0
);

-- ========================================
-- IAM: Actions
-- ========================================
CREATE TABLE IF NOT EXISTS iam_action (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)   NOT NULL UNIQUE,
    description VARCHAR(500),
    tenant_id   VARCHAR(100),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version     BIGINT        NOT NULL DEFAULT 0
);

-- ========================================
-- IAM: Users
-- ========================================
CREATE TABLE IF NOT EXISTS iam_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    tenant_id  VARCHAR(100),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version    BIGINT       NOT NULL DEFAULT 0,
    UNIQUE (username, tenant_id),
    UNIQUE (email, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_user_email ON iam_user (email);

-- ========================================
-- IAM: User-Role Junction Table
-- ========================================
CREATE TABLE IF NOT EXISTS iam_user_roles (
    user_id BIGINT NOT NULL REFERENCES iam_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES iam_role (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- ========================================
-- Audit: Audit Log
-- ========================================
CREATE TABLE IF NOT EXISTS audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(100) NOT NULL,
    entity_type    VARCHAR(255),
    entity_id      VARCHAR(255),
    user_id        VARCHAR(100),
    tenant_id      VARCHAR(100),
    timestamp      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details        TEXT,
    correlation_id VARCHAR(100),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version        BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_audit_log_event_type  ON audit_log (event_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_tenant      ON audit_log (tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user        ON audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp   ON audit_log (timestamp DESC);
